export const cursantes: Array <{nombre:string, apellido:string, aprobo:boolean}>=[
    {nombre:"Juan",apellido:"cortez", aprobo:false},
    { nombre: "María", apellido: "Gómez", aprobo: true },
    { nombre: "Pedro", apellido: "Rodríguez", aprobo: false },
    { nombre: "Luisa", apellido: "Martínez", aprobo: true },
    { nombre: "Pedro", apellido: "Gómez", aprobo: true },
    { nombre: "Ana", apellido: "López", aprobo: false },
    { nombre: "Carlos", apellido: "Hernández", aprobo: true },
    { nombre: "Laura", apellido: "Pérez", aprobo: false },
    { nombre: "José", apellido: "Ramírez", aprobo: true },
    { nombre: "Mariana", apellido: "Torres", aprobo: false },
    { nombre: "Diego", apellido: "Vargas", aprobo: true },
    { nombre: "Fernanda", apellido: "Díaz", aprobo: false },
    { nombre: "Santiago", apellido: "Mendoza", aprobo: true },
    { nombre: "Valentina", apellido: "García", aprobo: false },
    { nombre: "Roberto", apellido: "Ortega", aprobo: true },
    { nombre: "Marcela", apellido: "Navarro", aprobo: false },
    { nombre: "Gonzalo", apellido: "Rojas", aprobo: true },
    { nombre: "Carolina", apellido: "Silva", aprobo: false },
    { nombre: "Andrés", apellido: "Gutiérrez", aprobo: true },
    { nombre: "Daniela", apellido: "Castillo", aprobo: false },
    { nombre: "Javier", apellido: "Sánchez", aprobo: true },
    { nombre: "Paola", apellido: "Martínez", aprobo: false },
    { nombre: "Ricardo", apellido: "Vega", aprobo: true },
    { nombre: "Isabel", apellido: "Paredes", aprobo: false },
    { nombre: "Eduardo", apellido: "Fuentes", aprobo: true },
    { nombre: "Camila", apellido: "Jiménez", aprobo: false },
    { nombre: "Hugo", apellido: "Mora", aprobo: true },
    { nombre: "Natalia", apellido: "Lara", aprobo: false },
    { nombre: "Mario", apellido: "Castro", aprobo: true },
    { nombre: "Catalina", apellido: "Ortiz", aprobo: false },
    { nombre: "Pablo", apellido: "Reyes", aprobo: true },
    { nombre: "Alejandra", apellido: "Herrera", aprobo: false },
    { nombre: "Ignacio", apellido: "Guerra", aprobo: true },
    { nombre: "Gabriela", apellido: "Cruz", aprobo: false }
]